feat: sending email when tender is finished
PSW-Organization-8/integration-app pull request #52
Opened 2022-01-11 17:01 UTC by mmitic99

2022-01-11 19:08 UTC, MatijaUskokovic approved these changes

2022-01-13 15:53 UTC, djordjekrsmanovic commented on HospitalInformationSystem/IntegrationClassLib/Parthership/Service/EmailService.cs
> +            //google security :(
You can see this link https://help.groovehq.com/help/why-wont-my-gmail-smtp-settings-work and use smtp with google link. 
But never mind if it works with outlook.

2022-01-13 15:55 UTC, djordjekrsmanovic requested changes

2022-01-13 15:55 UTC, djordjekrsmanovic commented on HospitalInformationSystem/IntegrationClassLib/Parthership/Service/EmailService.cs
> +            emailCredentials = new NetworkCredential("psworganisation8@outlook.com", "pswFtnOrganisation8");
Replace with env variables.

2022-01-13 16:35 UTC, mmitic99 commented on HospitalInformationSystem/IntegrationClassLib/Parthership/Service/EmailService.cs
> +            //google security :(
Poslalo je 5-6 email-a preko google, i posle toga nije htelo više.

2022-01-13 17:23 UTC, djordjekrsmanovic approved these changes

2022-01-13 17:32 UTC, merged